import type { SeedEntity } from "@/lib/compiler/types";
import { FINANCE_SEED_ENTITIES } from "./finance";

export const SEED_ENTITIES: SeedEntity[] = [
  { slug: "openai", name: "OpenAI", entityType: "lab", description: "San Francisco AI lab behind GPT, o-series, and ChatGPT.", aliases: ["OAI"], officialDomains: ["openai.com"] },
  { slug: "anthropic", name: "Anthropic", entityType: "lab", description: "AI lab behind Claude.", aliases: [], officialDomains: ["anthropic.com"] },
  { slug: "google-deepmind", name: "Google DeepMind", entityType: "lab", description: "Google's AI research lab; Gemini and AlphaFold.", aliases: ["DeepMind"], officialDomains: ["deepmind.google", "deepmind.com"] },
  { slug: "xai", name: "xAI", entityType: "lab", description: "AI lab behind Grok.", aliases: [], officialDomains: ["x.ai"] },
  { slug: "meta-ai", name: "Meta AI", entityType: "lab", description: "Meta's AI org; Llama family.", aliases: ["Facebook AI", "FAIR"], officialDomains: ["ai.meta.com", "llama.com"] },
  { slug: "mistral-ai", name: "Mistral AI", entityType: "lab", description: "Paris AI lab.", aliases: ["Mistral"], officialDomains: ["mistral.ai"] },
  { slug: "cohere", name: "Cohere", entityType: "lab", description: "Enterprise LLM lab.", aliases: [], officialDomains: ["cohere.com"] },
  { slug: "stability-ai", name: "Stability AI", entityType: "lab", description: "Generative image/video lab.", aliases: [], officialDomains: ["stability.ai"] },
  { slug: "huggingface", name: "Hugging Face", entityType: "lab", description: "Model hub and open ML platform.", aliases: ["HF"], officialDomains: ["huggingface.co"] },
  { slug: "perplexity", name: "Perplexity", entityType: "lab", description: "Answer-engine company.", aliases: [], officialDomains: ["perplexity.ai"] },
  { slug: "ai21", name: "AI21 Labs", entityType: "lab", description: "Jamba / Jurassic lab.", aliases: ["AI21"], officialDomains: ["ai21.com"] },
  { slug: "databricks", name: "Databricks", entityType: "lab", description: "Data platform; MosaicML / DBRX.", aliases: ["MosaicML"], officialDomains: ["databricks.com"] },
  { slug: "nvidia", name: "NVIDIA", entityType: "infra", description: "GPUs, CUDA, NIM, and AI systems.", aliases: ["Nvidia"], officialDomains: ["nvidia.com"] },
  { slug: "microsoft-ai", name: "Microsoft AI", entityType: "lab", description: "Microsoft AI + Azure OpenAI.", aliases: ["Azure OpenAI"], officialDomains: ["microsoft.com", "azure.microsoft.com"] },
  { slug: "amazon-bedrock", name: "Amazon Bedrock", entityType: "infra", description: "AWS managed model platform.", aliases: ["Bedrock"], officialDomains: ["aws.amazon.com"] },
  { slug: "apple-intelligence", name: "Apple Intelligence", entityType: "lab", description: "Apple on-device and Private Cloud Compute AI.", aliases: [], officialDomains: ["apple.com"] },
  { slug: "z-ai", name: "Z.ai", entityType: "lab", description: "Zhipu / Z.ai, lab behind the GLM model family.", aliases: ["Zhipu", "Zhipu AI", "BigModel"], officialDomains: ["z.ai", "bigmodel.cn"] },
  { slug: "moonshot", name: "Moonshot AI", entityType: "lab", description: "Kimi lab.", aliases: ["Moonshot", "Kimi"], officialDomains: ["moonshot.ai", "kimi.com"] },
  { slug: "alibaba-qwen", name: "Alibaba Qwen", entityType: "lab", description: "Qwen model family.", aliases: ["Qwen", "Tongyi"], officialDomains: ["qwen.ai", "alibaba.com"] },
  { slug: "deepseek", name: "DeepSeek", entityType: "lab", description: "Hangzhou lab; V3 / R1.", aliases: [], officialDomains: ["deepseek.com"] },
  { slug: "minimax", name: "MiniMax", entityType: "lab", description: "MiniMax models and speech.", aliases: [], officialDomains: ["minimax.io", "minimaxi.com"] },
  { slug: "gpt-5", name: "GPT-5", entityType: "model", description: "OpenAI GPT-5 family.", aliases: ["GPT-5.4"], officialDomains: ["openai.com"] },
  { slug: "claude-4", name: "Claude 4", entityType: "model", description: "Anthropic Claude 4 family.", aliases: ["Claude Sonnet", "Claude Opus"], officialDomains: ["anthropic.com"] },
  { slug: "gemini-3", name: "Gemini", entityType: "model", description: "Google Gemini model family.", aliases: ["Gemini 3"], officialDomains: ["deepmind.google", "ai.google.dev"] },
  { slug: "grok-4", name: "Grok", entityType: "model", description: "xAI Grok model family.", aliases: ["Grok 4"], officialDomains: ["x.ai"] },
  { slug: "llama-4", name: "Llama", entityType: "model", description: "Meta Llama family.", aliases: ["Llama 4"], officialDomains: ["llama.com", "ai.meta.com"] },
  {
    slug: "glm-5-3",
    name: "GLM-5.3",
    entityType: "model",
    description: "Z.ai GLM-5.3: current flagship GLM, routed on Vercel AI Gateway as zai/glm-5.3.",
    aliases: ["GLM 5.3", "glm-5.3", "zai/glm-5.3"],
    officialDomains: ["z.ai", "bigmodel.cn", "vercel.com"],
    launchDemo: true,
  },
  { slug: "glm-5-2", name: "GLM-5.2", entityType: "model", description: "Prior GLM generation; Eve default for a period.", aliases: ["GLM 5.2", "zai/glm-5.2"], officialDomains: ["z.ai", "vercel.com"] },
  { slug: "deepseek-v3", name: "DeepSeek-V3", entityType: "model", description: "DeepSeek V3 / R1 family.", aliases: ["DeepSeek R1"], officialDomains: ["deepseek.com"] },
  { slug: "qwen-3", name: "Qwen", entityType: "model", description: "Alibaba Qwen model line.", aliases: ["Qwen3"], officialDomains: ["qwen.ai"] },
  { slug: "mistral-large", name: "Mistral Large", entityType: "model", description: "Mistral flagship text model.", aliases: [], officialDomains: ["mistral.ai"] },
  { slug: "vercel-ai-gateway", name: "Vercel AI Gateway", entityType: "infra", description: "Unified model router and provider-executed tools, including Exa search.", aliases: ["AI Gateway"], officialDomains: ["vercel.com", "ai-gateway.vercel.sh"] },
  { slug: "eve", name: "Vercel Eve", entityType: "infra", description: "Vercel filesystem-first agent framework.", aliases: ["eve"], officialDomains: ["eve.dev", "vercel.com"] },
  { slug: "aws-bedrock", name: "AWS Bedrock", entityType: "infra", description: "Managed multi-model API on AWS.", aliases: [], officialDomains: ["aws.amazon.com"] },
  { slug: "azure-ai-foundry", name: "Azure AI Foundry", entityType: "infra", description: "Microsoft Azure model catalog and hosting.", aliases: ["Azure AI"], officialDomains: ["azure.microsoft.com"] },
  { slug: "google-vertex-ai", name: "Google Vertex AI", entityType: "infra", description: "Google Cloud model platform.", aliases: ["Vertex AI"], officialDomains: ["cloud.google.com"] },
  { slug: "groq", name: "Groq", entityType: "infra", description: "LPU inference.", aliases: [], officialDomains: ["groq.com"] },
  { slug: "together-ai", name: "Together AI", entityType: "infra", description: "Open-model inference cloud.", aliases: ["Together"], officialDomains: ["together.ai"] },
  { slug: "fireworks", name: "Fireworks AI", entityType: "infra", description: "Fast open-model inference.", aliases: [], officialDomains: ["fireworks.ai"] },
  { slug: "cerebras", name: "Cerebras", entityType: "infra", description: "Wafer-scale inference.", aliases: [], officialDomains: ["cerebras.ai"] },
  { slug: "coreweave", name: "CoreWeave", entityType: "infra", description: "GPU cloud.", aliases: [], officialDomains: ["coreweave.com"] },
  { slug: "openrouter", name: "OpenRouter", entityType: "infra", description: "Multi-provider LLM router.", aliases: [], officialDomains: ["openrouter.ai"] },
  { slug: "alphafold", name: "AlphaFold", entityType: "research", description: "DeepMind protein-structure system.", aliases: [], officialDomains: ["deepmind.google"] },
  { slug: "swe-bench", name: "SWE-bench", entityType: "research", description: "Software-engineering agent benchmark.", aliases: ["SWE-bench Verified"], officialDomains: ["swebench.com"] },
  { slug: "mlperf", name: "MLPerf", entityType: "research", description: "MLCommons training and inference benchmarks.", aliases: [], officialDomains: ["mlcommons.org"] },
  { slug: "eu-ai-act", name: "EU AI Act", entityType: "policy", description: "European Union AI regulation.", aliases: ["Artificial Intelligence Act"], officialDomains: ["europa.eu"] },
  { slug: "nist-ai-rmf", name: "NIST AI RMF", entityType: "policy", description: "US NIST AI Risk Management Framework.", aliases: ["AI RMF"], officialDomains: ["nist.gov"] },
  { slug: "ca-sb-53", name: "California AI bills", entityType: "policy", description: "California frontier-model legislation.", aliases: ["SB 53", "SB 1047"], officialDomains: ["ca.gov"] },
  { slug: "uk-aisi", name: "UK AISI", entityType: "policy", description: "UK AI Security Institute.", aliases: ["AISI"], officialDomains: ["aisi.gov.uk", "gov.uk"] },
  { slug: "nyt-v-openai", name: "NYT v. OpenAI", entityType: "policy", description: "Copyright litigation over training data.", aliases: ["New York Times v OpenAI"], officialDomains: ["nytimes.com"] },
];

export const LAUNCH_DEMO_SLUG =
  SEED_ENTITIES.find((entity) => entity.launchDemo)?.slug ?? "glm-5-3";

export function getEntityBySlug(slug: string): SeedEntity | undefined {
  return SEED_ENTITIES.find((row) => row.slug === slug) ?? FINANCE_SEED_ENTITIES.find((row) => row.slug === slug);
}
